#!/usr/bin/env python3
"""
CV draft generator prototype for the Job Search Automation MVP.

Input:
  - cv_strategy.yaml generated by strategy_generator.py
  - job_standardized.yaml generated by matcher.py
  - v0.1 data files

Output:
  - cv_draft.yaml
  - cv_draft.txt (clean paste-ready text)

This prototype is intentionally conservative:
  - It uses selected evidence from cv_strategy.yaml.
  - It does not invent tools, titles, clients, certifications, or outcomes.
  - It keeps evidence IDs attached to generated sections.
  - It uses the strategy as the approval artifact before drafting.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Set, Tuple

from .paths import resolve_data_dir

try:
    import yaml  # type: ignore
except ModuleNotFoundError:  # pragma: no cover
    yaml = None


PROGRAMMING_TERMS = {
    "c", "c++", "c#", "python", "bash", "perl", "fortran", "matlab", "simulink",
    "sql", "javascript", "typescript", "java", "unix", "go", "rust"
}

SOFT_TERMS = {
    "technical leadership", "cross-functional collaboration", "collaboration", "mentoring",
    "coaching", "stakeholder", "root-cause analysis", "root cause analysis", "agile",
    "scrum", "safe", "pi planning", "innovation leadership", "onboarding", "training",
    "technical design reviews", "process ownership", "requirements refinement"
}

KNOWLEDGE_PRIORITY = [
    "ISO 26262", "V-model", "AUTOSAR", "Vector DaVinci", "DaVinci", "Vector", "SIL", "HIL",
    "CI/CD", "unit testing", "verification and validation", "verification", "validation",
    "embedded systems", "embedded", "real-time", "safety-critical", "Jira", "Jenkins", "Git"
]


def load_yaml(path: Path) -> Dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        return yaml.safe_load(text) or {}
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Cannot read {path.name} without PyYAML because it is not JSON-compatible YAML. "
            "Install PyYAML with: python -m pip install pyyaml"
        ) from exc


def write_yaml(path: Path, data: Dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8") as f:
        if yaml is not None:
            yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True, width=110)
        else:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")


def norm(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value).lower()).strip()


def unique_preserve(items: Iterable[Any]) -> List[Any]:
    seen: Set[str] = set()
    out: List[Any] = []
    for item in items:
        if item in (None, ""):
            continue
        key = norm(item)
        if key not in seen:
            seen.add(key)
            out.append(item)
    return out


def get_nested(d: Dict[str, Any], *keys: str, default: Any = None) -> Any:
    cur: Any = d
    for key in keys:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    return cur


def find_job_id(strategy: Dict[str, Any]) -> str:
    return get_nested(strategy, "cv_strategy", "job_id", default="job_unknown")


def selected_evidence(strategy: Dict[str, Any]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for role in get_nested(strategy, "cv_strategy", "experience_plan", default=[]) or []:
        for ev in role.get("evidence_to_use", []) or []:
            ev_copy = dict(ev)
            ev_copy["role_group_id"] = role.get("role_group_id")
            ev_copy["role_header"] = role.get("role_header")
            out.append(ev_copy)
    return out


def selected_role_groups(strategy: Dict[str, Any]) -> List[Dict[str, Any]]:
    return get_nested(strategy, "cv_strategy", "experience_plan", default=[]) or []


def evidence_text_by_id(strategy: Dict[str, Any]) -> Dict[str, str]:
    return {ev.get("evidence_id"): ev.get("text", "") for ev in selected_evidence(strategy) if ev.get("evidence_id")}


def sentence_from_focus(focus: List[str]) -> str:
    clean = [f for f in unique_preserve(focus) if f]
    if not clean:
        return "selected engineering domains"
    # Keep summary compact.
    preferred = []
    for item in clean:
        low = norm(item)
        if low in {"embedded", "embedded systems", "embedded software development"}:
            preferred.append("embedded software")
        elif low in {"verification", "validation", "verification and validation"}:
            preferred.append("verification and validation")
        elif low in {"ci/cd"}:
            preferred.append("CI/CD")
        elif low in {"iso 26262"}:
            preferred.append("ISO 26262")
        elif low in {"sil", "hil"}:
            preferred.append(item.upper())
        elif item not in preferred:
            preferred.append(item)
    clean = unique_preserve(preferred)[:5]
    if len(clean) == 1:
        return str(clean[0])
    return ", ".join(str(x) for x in clean[:-1]) + " and " + str(clean[-1])


def build_summary(employee: Dict[str, Any], strategy: Dict[str, Any]) -> Tuple[str, List[str]]:
    emp = employee.get("employee", employee)
    years = emp.get("years_experience", "")
    focus = []
    focus.extend(get_nested(strategy, "cv_strategy", "job_positioning", "primary_technical_focus", default=[]) or [])
    focus.extend(get_nested(strategy, "cv_strategy", "job_positioning", "secondary_technical_focus", default=[]) or [])
    mandatory = get_nested(strategy, "cv_strategy", "mandatory_cv_terms", default=[]) or []
    for term in mandatory:
        if norm(term) in {"c++", "c", "iso 26262", "ci/cd", "sil", "hil", "vector davinci", "autosar"}:
            focus.append(term)

    roles = selected_role_groups(strategy)
    evidence = selected_evidence(strategy)
    evidence_ids = [ev.get("evidence_id") for ev in evidence[:6] if ev.get("evidence_id")]
    role_names = [r.get("role_group_id", "") for r in roles]
    role_phrase = "recent Volvo and Ericsson assignments"
    if any("GE" in r for r in role_names):
        role_phrase += ", supported by foundational GE control-systems experience"

    focus_phrase = sentence_from_focus(focus)
    sentences = []
    if years:
        sentences.append(f"Senior software engineer with {years} years of experience in {focus_phrase}.")
    else:
        sentences.append(f"Senior software engineer with experience in {focus_phrase}.")

    mandatory_clean = [t for t in unique_preserve(mandatory) if norm(t) in {
        "c++", "c", "jira", "git", "jenkins", "vector", "vector davinci", "davinci", "autosar",
        "ci/cd", "agile", "iso 26262", "sil", "hil", "unit testing"
    }]
    if mandatory_clean:
        sentences.append("Selected experience covers " + ", ".join(mandatory_clean[:8]) + ".")

    sentences.append(f"The CV emphasis is based on {role_phrase}, with claims grounded in selected project evidence.")
    return " ".join(sentences), evidence_ids


def classify_term(term: str) -> str:
    low = norm(term)
    if low in PROGRAMMING_TERMS:
        return "Programming"
    if low in SOFT_TERMS or "leadership" in low or "collaboration" in low or "coaching" in low:
        return "Soft Skills"
    return "Knowledge"


def build_tech_competence(strategy: Dict[str, Any]) -> Dict[str, List[str]]:
    raw = get_nested(strategy, "cv_strategy", "tech_competence_inclusion", default={}) or {}
    mandatory = get_nested(strategy, "cv_strategy", "mandatory_cv_terms", default=[]) or []
    columns: Dict[str, List[str]] = {"Programming": [], "Knowledge": [], "Soft Skills": []}

    # Start with strategy suggestions, but reclassify obvious misplaced terms.
    for _col, terms in raw.items():
        for term in terms or []:
            col = classify_term(str(term))
            columns[col].append(term)

    # Add mandatory terms, reclassified, so explicit tools requested by the job are preserved.
    for term in mandatory:
        col = classify_term(str(term))
        columns[col].append(term)

    # Clean up non-programming artifacts.
    columns["Programming"] = [t for t in columns["Programming"] if norm(t) in PROGRAMMING_TERMS]

    # Prefer recognizable knowledge items and mandatory explicit terms.
    knowledge = columns["Knowledge"]
    ordered_knowledge = []
    for p in KNOWLEDGE_PRIORITY:
        for item in knowledge:
            if norm(item) == norm(p):
                ordered_knowledge.append(item)
    ordered_knowledge.extend(knowledge)
    columns["Knowledge"] = ordered_knowledge

    for col in columns:
        columns[col] = unique_preserve(columns[col])[:10]
    return columns


def build_experience(strategy: Dict[str, Any]) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for role in selected_role_groups(strategy):
        bullets = []
        for ev in role.get("evidence_to_use", []) or []:
            text = ev.get("text", "").strip()
            if not text:
                continue
            # Keep evidence text mostly unchanged. The prototype avoids creative rewriting.
            if not text.endswith("."):
                text += "."
            bullets.append({
                "text": text,
                "evidence_links": [ev.get("evidence_id")],
                "source_block_id": ev.get("block_id"),
            })
        out.append({
            "role_group_id": role.get("role_group_id"),
            "role_header": role.get("role_header"),
            "planned_bullet_count": role.get("planned_bullet_count"),
            "bullets": bullets[: int(role.get("planned_bullet_count") or len(bullets))],
        })
    return out


def validate_draft(strategy: Dict[str, Any], tech: Dict[str, List[str]], experience: List[Dict[str, Any]], summary: str) -> Dict[str, Any]:
    mandatory = [str(t) for t in get_nested(strategy, "cv_strategy", "mandatory_cv_terms", default=[]) or []]
    cv_text = summary + "\n" + "\n".join(sum((tech[col] for col in tech), [])) + "\n" + "\n".join(
        bullet["text"] for role in experience for bullet in role.get("bullets", [])
    )
    cv_low = norm(cv_text)

    surfaced = []
    missing = []
    for term in mandatory:
        if norm(term) in cv_low:
            surfaced.append(term)
        else:
            # Some terms may be supported by strategy but intentionally omitted for one-page or alias reasons.
            missing.append(term)

    total_bullets = sum(len(role.get("bullets", [])) for role in experience)
    return {
        "unsupported_claims": [],
        "mandatory_terms_surfaced": unique_preserve(surfaced),
        "mandatory_terms_not_surfaced": unique_preserve(missing),
        "role_group_count": len(experience),
        "bullet_count": total_bullets,
        "one_page_estimate": "pass" if len(summary.split()) < 85 and total_bullets <= 11 else "review",
        "grounding_note": "Summary and bullets are linked to selected strategy evidence; this prototype does not invent new experience.",
    }


def render_text(draft: Dict[str, Any]) -> str:
    cv = draft["cv_draft"]
    sections = cv["sections"]
    lines: List[str] = []
    lines.append("SECTION A — Professional Summary")
    lines.append(sections["professional_summary"]["text"])
    lines.append("")
    lines.append("SECTION B — Tech Competence")
    tech = sections["tech_competence"]
    for col in ["Programming", "Knowledge", "Soft Skills"]:
        lines.append(f"{col}: " + "; ".join(tech.get(col, [])))
    lines.append("")
    lines.append("SECTION C — Experience")
    for role in sections["experience"]:
        lines.append(role.get("role_header", role.get("role_group_id", "")))
        for bullet in role.get("bullets", []):
            lines.append(f"- {bullet['text']}")
        lines.append("")
    lines.append("SECTION D — Validation")
    val = cv.get("validation", {})
    lines.append(f"One-page estimate: {val.get('one_page_estimate')}")
    if val.get("mandatory_terms_not_surfaced"):
        lines.append("Mandatory terms not surfaced: " + ", ".join(val["mandatory_terms_not_surfaced"]))
    else:
        lines.append("Mandatory terms not surfaced: none")
    return "\n".join(lines).strip() + "\n"


def generate_draft(strategy: Dict[str, Any], employee: Dict[str, Any], job_std: Dict[str, Any]) -> Dict[str, Any]:
    cv_strategy = strategy.get("cv_strategy", strategy)
    job_id = cv_strategy.get("job_id", "job_unknown")
    employee_id = cv_strategy.get("employee_id", get_nested(employee, "employee", "employee_id", default="employee_unknown"))
    summary, summary_evidence = build_summary(employee, strategy)
    tech = build_tech_competence(strategy)
    experience = build_experience(strategy)
    validation = validate_draft(strategy, tech, experience, summary)

    return {
        "cv_draft": {
            "draft_id": f"draft_{job_id}",
            "job_id": job_id,
            "employee_id": employee_id,
            "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
            "status": "draft_for_human_review",
            "input_refs": {
                "cv_strategy": f"{job_id}.cv_strategy.yaml",
                "job_standardized": f"{job_id}.job_standardized.yaml",
                "employee_profile": "employee_profile.yaml",
                "experience_database": "experience_database.yaml",
                "cv_generation_policy": "cv_generation_policy.yaml",
            },
            "sections": {
                "professional_summary": {
                    "text": summary,
                    "evidence_links": summary_evidence,
                },
                "tech_competence": tech,
                "experience": experience,
            },
            "validation": validation,
            "notes_for_reviewer": [
                "Review whether the summary is sufficiently tailored and not over-anchored to unrelated domains.",
                "Check mandatory terms not surfaced; decide whether they should appear in tech competence or bullets.",
                "The prototype keeps bullets close to evidence text rather than rewriting creatively.",
            ],
        }
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate cv_draft.yaml from cv_strategy.yaml")
    parser.add_argument("--cv-strategy", required=True, help="Path to cv_strategy.yaml")
    parser.add_argument("--job-standardized", required=False, help="Optional path to job_standardized.yaml")
    parser.add_argument("--data-dir", default="data", help="Directory containing employee_profile.yaml")
    parser.add_argument("--out-dir", default="outputs/single", help="Output directory")
    args = parser.parse_args()

    strategy_path = Path(args.cv_strategy)
    data_dir = resolve_data_dir(args.data_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    strategy = load_yaml(strategy_path)
    employee = load_yaml(data_dir / "employee_profile.yaml")
    job_std = load_yaml(Path(args.job_standardized)) if args.job_standardized else {}

    draft = generate_draft(strategy, employee, job_std)
    job_id = draft["cv_draft"]["job_id"]
    yaml_path = out_dir / f"{job_id}.cv_draft.yaml"
    text_path = out_dir / f"{job_id}.cv_draft.txt"
    write_yaml(yaml_path, draft)
    text_path.write_text(render_text(draft), encoding="utf-8")

    print(f"Wrote {yaml_path}")
    print(f"Wrote {text_path}")


if __name__ == "__main__":
    main()
