#!/usr/bin/env python3
"""Run the post-review CV pipeline for selected jobs.

Input:
  - review_queue.csv generated by run_job_batch.py
  - one *.job_standardized.yaml and *.match_result.yaml per job
  - v0.1 data files

Output, for every row whose review_status is prepare_cv by default:
  - *.cv_strategy.yaml
  - *.cv_draft.yaml
  - *.cv_draft.txt
  - *.mpya_cv.html
  - selected_cv_pipeline_report.csv
  - selected_cv_pipeline_report.html

This script makes the review queue actionable. It intentionally starts from
human review decisions and does not generate CVs for every discovered job.
"""
from __future__ import annotations

import argparse
import csv
import html
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Set

from . import cv_draft_generator, cv_llm_orchestrator, cv_llm_routing, mpya_cv_renderer, strategy_generator
from .paths import default_assets_dir, resolve_data_dir


def read_review_queue(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def write_review_queue(path: Path, rows: List[Dict[str, str]]) -> None:
    if not rows:
        return
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def mark_top_rows(rows: List[Dict[str, str]], count: int, min_score: int) -> int:
    """Mark the top N rows as prepare_cv for quick testing."""
    if count <= 0:
        return 0
    def score(row: Dict[str, str]) -> int:
        try:
            return int(float(row.get("overall_score", "0") or 0))
        except ValueError:
            return 0
    ranked = sorted(rows, key=score, reverse=True)
    marked = 0
    for row in ranked:
        if marked >= count:
            break
        if score(row) < min_score:
            continue
        row["review_status"] = "prepare_cv"
        marked += 1
    return marked


def find_input_files(job_id: str, batch_dir: Path) -> tuple[Path, Path]:
    job_std = batch_dir / f"{job_id}.job_standardized.yaml"
    match = batch_dir / f"{job_id}.match_result.yaml"
    if not job_std.exists():
        raise FileNotFoundError(f"Missing standardized job file: {job_std}")
    if not match.exists():
        raise FileNotFoundError(f"Missing match result file: {match}")
    return job_std, match


def generate_for_job(job_id: str, job_std_path: Path, match_path: Path, data_dir: Path, out_dir: Path) -> Dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    data_dir = resolve_data_dir(data_dir)

    job_std = strategy_generator.load_yaml(job_std_path)
    match_result = strategy_generator.load_yaml(match_path)
    exp = strategy_generator.load_yaml(data_dir / "experience_database.yaml")
    policy = strategy_generator.load_yaml(data_dir / "cv_generation_policy.yaml")
    routing_plan = cv_llm_routing.build_routing_plan(policy)

    strategy = strategy_generator.build_strategy(job_std, match_result, exp, policy)
    strategy_path = out_dir / f"{job_id}.cv_strategy.yaml"
    strategy_generator.write_yaml(strategy_path, strategy)

    employee = cv_draft_generator.load_yaml(data_dir / "employee_profile.yaml")
    llm_steps = cv_llm_orchestrator.run_steps_1_to_6(
        strategy=strategy,
        job_std=job_std,
        employee=employee,
        policy=policy,
    )
    llm_steps_path = out_dir / f"{job_id}.cv_llm_steps.yaml"
    strategy_generator.write_yaml(llm_steps_path, {"cv_llm_steps": llm_steps})

    draft = cv_draft_generator.generate_draft(strategy, employee, job_std)
    draft_root = draft.get("cv_draft", draft)
    sections = draft_root.get("sections", {})
    step5 = ((llm_steps.get("steps", {}) or {}).get("summary_adaptation", {}) or {}).get("result", {})
    summary_text = step5.get("adapted_professional_summary")
    if summary_text and isinstance(sections.get("professional_summary"), dict):
        sections["professional_summary"]["text"] = str(summary_text)
    step6 = ((llm_steps.get("steps", {}) or {}).get("experience_generation", {}) or {}).get("result", {})
    llm_roles = step6.get("experience_sections", []) if isinstance(step6, dict) else []
    if isinstance(llm_roles, list) and llm_roles:
        role_map: Dict[str, Dict[str, Any]] = {}
        for role in sections.get("experience", []) or []:
            rgid = role.get("role_group_id")
            if rgid:
                role_map[str(rgid)] = role
        for llm_role in llm_roles:
            if not isinstance(llm_role, dict):
                continue
            rgid = str(llm_role.get("role_group_id", "") or "")
            if not rgid or rgid not in role_map:
                continue
            bullets = []
            for b in llm_role.get("bullets", []) or []:
                text = str(b or "").strip()
                if text:
                    bullets.append({"text": text, "evidence_links": [], "source_block_id": None})
            if bullets:
                role_map[rgid]["bullets"] = bullets[:6]
    step7 = ((llm_steps.get("steps", {}) or {}).get("tech_competence_generation", {}) or {}).get("result", {})
    llm_tech = step7.get("tech_competence") if isinstance(step7, dict) else None
    if isinstance(llm_tech, dict):
        tech = sections.get("tech_competence", {})
        for col in ["Programming", "Knowledge", "Soft Skills"]:
            vals = llm_tech.get(col)
            if isinstance(vals, list) and vals:
                tech[col] = [str(v) for v in vals]
        sections["tech_competence"] = tech

    draft_path = out_dir / f"{job_id}.cv_draft.yaml"
    draft_text_path = out_dir / f"{job_id}.cv_draft.txt"
    cv_draft_generator.write_yaml(draft_path, draft)
    draft_text_path.write_text(cv_draft_generator.render_text(draft), encoding="utf-8")

    draft_root = draft.get("cv_draft", draft)
    static_path = data_dir / "consultancy_static_profile.yaml"
    static_data = mpya_cv_renderer.load_yaml(static_path) if static_path.exists() else {}
    assets_dir = default_assets_dir()
    html_path = out_dir / f"{job_id}.mpya_cv.html"
    html_path.write_text(
        mpya_cv_renderer.render_html(draft_root, exp, static_data, employee, assets_dir),
        encoding="utf-8",
    )

    selected = strategy.get("cv_strategy", {}).get("selected_role_groups", [])
    mandatory = strategy.get("cv_strategy", {}).get("mandatory_cv_terms", [])
    validation = draft_root.get("validation", {})
    return {
        "job_id": job_id,
        "cv_strategy": str(strategy_path),
        "cv_draft_yaml": str(draft_path),
        "cv_draft_txt": str(draft_text_path),
        "mpya_cv_html": str(html_path),
        "cv_llm_steps_yaml": str(llm_steps_path),
        "selected_role_groups": ", ".join([str(x.get("role_group_id", "")) for x in selected]),
        "mandatory_terms": ", ".join([str(x) for x in mandatory[:14]]),
        "llm_text_source": "llm_or_fallback",
        "llm_calls_used": ((llm_steps.get("usage", {}) or {}).get("llm_calls_used", 0)),
        "llm_calls_budget": ((llm_steps.get("usage", {}) or {}).get("llm_calls_budget", 0)),
        "llm_routing_total_max_output_tokens": routing_plan.get("estimated_total_max_output_tokens", 0),
        "llm_routing_models": ", ".join(
            f"{s.get('step')}:{s.get('model')}" for s in routing_plan.get("steps", []) if isinstance(s, dict)
        ),
        "validation_status": "pass" if not validation.get("unsupported_claims") else "review",
        "one_page_estimate": validation.get("one_page_estimate", "unknown"),
    }


def write_report_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    fieldnames = [
        "job_id", "title", "company", "overall_score", "review_status", "selected_role_groups",
        "mandatory_terms", "llm_routing_total_max_output_tokens", "llm_routing_models",
        "llm_text_source", "llm_calls_used", "llm_calls_budget", "validation_status", "one_page_estimate",
        "cv_strategy", "cv_llm_steps_yaml", "cv_draft_yaml",
        "cv_draft_txt", "mpya_cv_html",
    ]
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in fieldnames})


def rel_link(path_text: str, base: Path) -> str:
    try:
        return Path(path_text).resolve().relative_to(base.resolve()).as_posix()
    except Exception:
        return path_text


def write_report_html(path: Path, rows: List[Dict[str, Any]]) -> None:
    cards = []
    for row in rows:
        cv_link = rel_link(str(row.get("mpya_cv_html", "")), path.parent)
        txt_link = rel_link(str(row.get("cv_draft_txt", "")), path.parent)
        strategy_link = rel_link(str(row.get("cv_strategy", "")), path.parent)
        cards.append(f"""
        <article class=\"card\">
          <div class=\"score\">{html.escape(str(row.get('overall_score', '')))}</div>
          <div class=\"body\">
            <h2>{html.escape(str(row.get('title', 'Untitled role')))}</h2>
            <p class=\"meta\">{html.escape(str(row.get('company', '')))} · job_id: {html.escape(str(row.get('job_id', '')))}</p>
            <p><b>Selected role groups:</b> {html.escape(str(row.get('selected_role_groups', '')))}</p>
            <p><b>Mandatory terms:</b> {html.escape(str(row.get('mandatory_terms', '')))}</p>
            <p><b>Validation:</b> {html.escape(str(row.get('validation_status', '')))} · {html.escape(str(row.get('one_page_estimate', '')))}</p>
            <p class=\"links\"><a href=\"{html.escape(cv_link)}\">Open MPYA CV</a> · <a href=\"{html.escape(txt_link)}\">CV draft text</a> · <a href=\"{html.escape(strategy_link)}\">CV strategy</a></p>
          </div>
        </article>
        """)
    body = "\n".join(cards) if cards else "<p>No rows were selected for CV preparation.</p>"
    path.write_text(f"""<!doctype html>
<html lang=\"en\"><head><meta charset=\"utf-8\"><title>Selected CV Pipeline Report</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 32px; background: #f4f4f1; color: #202020; }}
h1 {{ margin-bottom: 4px; }}
.hint {{ color: #555; margin-bottom: 24px; }}
.card {{ display: grid; grid-template-columns: 72px 1fr; background: white; border-radius: 14px; margin: 14px 0; box-shadow: 0 4px 18px rgba(0,0,0,.08); overflow: hidden; }}
.score {{ background: #a11b87; color: white; font-size: 28px; font-weight: 700; display: flex; align-items: center; justify-content: center; }}
.body {{ padding: 18px 22px; }}
h2 {{ margin: 0 0 4px; }}
.meta {{ color: #666; margin-top: 0; }}
a {{ color: #a11b87; font-weight: 700; text-decoration: none; }}
</style></head><body>
<h1>Selected CV Pipeline Report</h1>
<p class=\"hint\">Rows marked <code>prepare_cv</code> were converted into CV strategy, CV draft, and MPYA-style HTML CV files.</p>
{body}
</body></html>""", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run CV strategy, draft, and MPYA rendering for review_queue rows marked prepare_cv.")
    parser.add_argument("--review-queue", required=True, type=Path, help="Path to review_queue.csv")
    parser.add_argument("--batch-dir", required=True, type=Path, help="Folder containing *.job_standardized.yaml and *.match_result.yaml")
    parser.add_argument("--data-dir", required=True, type=Path, help="Directory containing data files")
    parser.add_argument("--out-dir", required=True, type=Path, help="Output folder for CV pipeline artifacts")
    parser.add_argument("--statuses", default="prepare_cv", help="Comma-separated review_status values to process")
    parser.add_argument("--auto-prepare-top", type=int, default=0, help="For testing: mark top N rows as prepare_cv before processing")
    parser.add_argument("--min-score", type=int, default=0, help="Minimum score when using --auto-prepare-top")
    parser.add_argument("--write-updated-review-queue", action="store_true", help="Write review_queue.updated.csv after auto marking")
    args = parser.parse_args()

    data_dir = resolve_data_dir(args.data_dir)
    rows = read_review_queue(args.review_queue)
    if args.auto_prepare_top:
        marked = mark_top_rows(rows, args.auto_prepare_top, args.min_score)
        print(f"Auto-marked {marked} row(s) as prepare_cv.")
        if args.write_updated_review_queue:
            updated = args.review_queue.with_name(args.review_queue.stem + ".updated.csv")
            write_review_queue(updated, rows)
            print(f"Wrote {updated}")

    wanted: Set[str] = {s.strip().lower() for s in args.statuses.split(",") if s.strip()}
    selected = [r for r in rows if (r.get("review_status", "") or "").strip().lower() in wanted]
    args.out_dir.mkdir(parents=True, exist_ok=True)

    report_rows: List[Dict[str, Any]] = []
    policy = strategy_generator.load_yaml(data_dir / "cv_generation_policy.yaml")
    routing_plan = cv_llm_routing.build_routing_plan(policy)
    routing_plan_path = args.out_dir / "llm_routing.plan.yaml"
    strategy_generator.write_yaml(routing_plan_path, {"llm_routing_plan": routing_plan})
    print(f"Wrote {routing_plan_path}")
    for row in selected:
        job_id = row.get("job_id", "").strip()
        if not job_id:
            print("Skipping row without job_id", file=sys.stderr)
            continue
        try:
            job_std, match = find_input_files(job_id, args.batch_dir)
            generated = generate_for_job(job_id, job_std, match, data_dir, args.out_dir)
            generated.update({
                "title": row.get("title", ""),
                "company": row.get("company", ""),
                "overall_score": row.get("overall_score", ""),
                "review_status": row.get("review_status", ""),
            })
            report_rows.append(generated)
            print(f"Generated CV pipeline artifacts for {job_id}: {row.get('title', '')}")
        except Exception as exc:
            print(f"ERROR processing {job_id}: {exc}", file=sys.stderr)

    csv_path = args.out_dir / "selected_cv_pipeline_report.csv"
    html_path = args.out_dir / "selected_cv_pipeline_report.html"
    write_report_csv(csv_path, report_rows)
    write_report_html(html_path, report_rows)
    print(f"Wrote {csv_path}")
    print(f"Wrote {html_path}")
    if not report_rows:
        print("No CVs were generated. Mark rows in review_queue.csv with review_status=prepare_cv, or use --auto-prepare-top 1 for testing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
