#!/usr/bin/env python3
"""
CV strategy generator prototype for the Job Search Automation MVP.

Input:
  - job_standardized.yaml generated by matcher.py
  - match_result.yaml generated by matcher.py
  - v0.1 YAML data files

Output:
  - cv_strategy.yaml

This prototype intentionally does NOT generate CV text. It creates a reviewable
intermediate artifact that decides:
  - which role groups should be used
  - which evidence items support the job
  - which explicit job tools must be surfaced
  - which summary angle and tech competence terms should be used
  - which topics should be de-emphasized
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Set, Tuple

from .paths import resolve_data_dir

try:
    import yaml  # type: ignore
except ModuleNotFoundError:  # pragma: no cover
    yaml = None


PROGRAMMING_HINTS = {
    "c", "c++", "c#", "python", "bash", "perl", "fortran", "matlab", "simulink",
    "sql", "javascript", "typescript", "java", "unix", "beacon7", "toolbox"
}

SOFT_SKILL_HINTS = {
    "technical leadership", "cross-functional", "collaboration", "mentoring", "coaching",
    "stakeholder", "root cause", "root-cause", "agile", "scrum", "safe", "pi planning",
    "process ownership", "innovation leadership", "onboarding", "training", "resource planning",
    "delivery commitments", "architecture", "technical design reviews"
}

DEEMPHASIS_RULES = [
    ("ai", ["autonomous driving", "heavy vehicles", "automotive", "pure people management"]),
    ("embedded", ["generic AI innovation", "patent support", "pure people management"]),
    ("verification", ["pure people management", "generic project coordination"]),
    ("technical lead", ["low-level tool lists without leadership context"]),
]


def load_yaml(path: Path) -> Dict[str, Any]:
    """Load YAML/JSON for the prototype.

    PyYAML is preferred. When PyYAML is not installed, this package stores the
    YAML files in JSON-compatible form so json.loads works. If you are using an
    older handwritten YAML file, install PyYAML with:
        python -m pip install pyyaml
    """
    text = path.read_text(encoding="utf-8")
    if yaml is not None:
        return yaml.safe_load(text) or {}
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Cannot read {path.name} without PyYAML because it is not "
            "JSON-compatible YAML. Install PyYAML with: python -m pip install pyyaml"
        ) from exc


def write_yaml(path: Path, data: Dict[str, Any]) -> None:
    with path.open("w", encoding="utf-8") as f:
        if yaml is not None:
            yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True, width=110)
        else:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")


def as_list(value: Any) -> List[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def norm(text: Any) -> str:
    return re.sub(r"\s+", " ", str(text).lower()).strip()


def unique_preserve(items: Iterable[Any]) -> List[Any]:
    seen: Set[str] = set()
    out: List[Any] = []
    for item in items:
        if item in [None, ""]:
            continue
        key = norm(item)
        if key not in seen:
            seen.add(key)
            out.append(item)
    return out


def get_nested(d: Dict[str, Any], *keys: str, default: Any = None) -> Any:
    cur: Any = d
    for key in keys:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    return cur


def flatten_strings(value: Any) -> List[str]:
    out: List[str] = []
    if isinstance(value, str):
        out.append(value)
    elif isinstance(value, list):
        for item in value:
            out.extend(flatten_strings(item))
    elif isinstance(value, dict):
        for item in value.values():
            out.extend(flatten_strings(item))
    return out


def index_experience(exp: Dict[str, Any]) -> Tuple[Dict[str, Dict[str, Any]], Dict[str, Dict[str, Any]], Dict[str, Dict[str, Any]]]:
    root = exp.get("experience_database", exp)
    role_groups = {rg["role_group_id"]: rg for rg in root.get("role_groups", [])}
    blocks: Dict[str, Dict[str, Any]] = {}
    evidence: Dict[str, Dict[str, Any]] = {}
    for rg in role_groups.values():
        for block in rg.get("blocks", []):
            block = dict(block)
            block["role_group_id"] = rg["role_group_id"]
            blocks[block["block_id"]] = block
            for ev in block.get("evidence_items", []):
                ev = dict(ev)
                ev["block_id"] = block["block_id"]
                ev["role_group_id"] = rg["role_group_id"]
                evidence[ev["evidence_id"]] = ev
    return role_groups, blocks, evidence


def extract_explicit_terms(job_std: Dict[str, Any], match_result: Dict[str, Any]) -> List[str]:
    explicit_terms = []
    explicit = get_nested(job_std, "job_standardized", "explicit_terms", default={}) or {}
    explicit_terms.extend(flatten_strings(explicit))
    # Include matcher-detected terms that may not have been in the explicit_terms object.
    matches = get_nested(match_result, "match_result", "matched_evidence", "explicit_term_matches", default=[]) or []
    explicit_terms.extend(m.get("job_term") for m in matches if isinstance(m, dict))
    return unique_preserve(explicit_terms)


def score_role_groups(match_result: Dict[str, Any], role_groups: Dict[str, Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    """Score role groups using the best match per unique job term.

    This avoids over-scoring older roles when the matcher finds many alias/supporting
    links for the same requirement. Exact evidence is intentionally worth much more
    than alias evidence, because CV strategy should surface concrete supported tools.
    """
    matches = get_nested(match_result, "match_result", "matched_evidence", "explicit_term_matches", default=[]) or []
    best_by_group_term: Dict[Tuple[str, str], Dict[str, Any]] = {}

    for m in matches:
        if not isinstance(m, dict):
            continue
        rgid = m.get("role_group_id")
        term = m.get("job_term")
        if not rgid or not term:
            continue
        key = (rgid, norm(term))
        existing = best_by_group_term.get(key)
        mtype = m.get("match_type", "match")
        weight = 3.0 if mtype == "exact" else 1.2
        existing_weight = 0.0
        if existing:
            existing_weight = 3.0 if existing.get("match_type") == "exact" else 1.2
        if existing is None or weight > existing_weight:
            best_by_group_term[key] = m

    scores: Dict[str, float] = defaultdict(float)
    matched_terms: Dict[str, Set[str]] = defaultdict(set)
    matched_blocks: Dict[str, Set[str]] = defaultdict(set)
    matched_evidence: Dict[str, Set[str]] = defaultdict(set)
    match_types: Dict[str, Counter] = defaultdict(Counter)

    for (rgid, _), m in best_by_group_term.items():
        mtype = m.get("match_type", "match")
        term = m.get("job_term")
        weight = 3.0 if mtype == "exact" else 1.2
        scores[rgid] += weight
        if term:
            matched_terms[rgid].add(term)
        if m.get("matched_block_id"):
            matched_blocks[rgid].add(m["matched_block_id"])
        for evid in m.get("evidence_ids", []) or []:
            matched_evidence[rgid].add(evid)
        match_types[rgid][mtype] += 1

    # Add modest recency and foundational support without overpowering explicit evidence.
    for rgid, rg in role_groups.items():
        recency_rank = int(rg.get("recency_rank", 99) or 99)
        if rgid in scores:
            scores[rgid] += max(0, 4 - recency_rank) * 0.8
            if rg.get("role_group_type") == "foundational":
                scores[rgid] += 0.8

    return {
        rgid: {
            "score": round(score, 2),
            "matched_terms": sorted(matched_terms[rgid]),
            "matched_blocks": sorted(matched_blocks[rgid]),
            "matched_evidence_ids": sorted(matched_evidence[rgid]),
            "match_types": dict(match_types[rgid]),
        }
        for rgid, score in scores.items()
    }

def select_role_groups(role_group_scores: Dict[str, Dict[str, Any]], role_groups: Dict[str, Dict[str, Any]], max_groups: int) -> List[str]:
    ranked = sorted(
        role_group_scores,
        key=lambda rgid: (
            role_group_scores[rgid]["score"],
            -int(role_groups.get(rgid, {}).get("recency_rank", 99) or 99),
        ),
        reverse=True,
    )
    selected = ranked[:max_groups]

    # Foundational role policy: include only if it actually matched evidence and supports the role.
    foundational = [rgid for rgid in ranked if role_groups.get(rgid, {}).get("role_group_type") == "foundational"]
    if foundational and foundational[0] not in selected:
        f = foundational[0]
        if role_group_scores[f]["score"] >= 4 and len(selected) >= max_groups:
            selected[-1] = f
        elif role_group_scores[f]["score"] >= 4:
            selected.append(f)
    return selected[:max_groups]


def evidence_text_blob(ev: Dict[str, Any]) -> str:
    return " ".join(flatten_strings({"text": ev.get("text", ""), "tags": ev.get("tags", [])}))


def select_evidence_for_role(
    rgid: str,
    role_group_scores: Dict[str, Dict[str, Any]],
    role_groups: Dict[str, Dict[str, Any]],
    evidence_index: Dict[str, Dict[str, Any]],
    mandatory_terms: List[str],
    bullet_target: int,
) -> List[Dict[str, Any]]:
    rg = role_groups[rgid]
    matched_ids = set(role_group_scores.get(rgid, {}).get("matched_evidence_ids", []))
    candidates: Dict[str, Dict[str, Any]] = {}
    for block in rg.get("blocks", []):
        for ev in block.get("evidence_items", []):
            candidates[ev["evidence_id"]] = ev

    scored: List[Tuple[float, str, Dict[str, Any]]] = []
    for evid, ev in candidates.items():
        blob = norm(evidence_text_blob(ev))
        score = 0.0
        if evid in matched_ids:
            score += 5.0
        for term in mandatory_terms:
            if norm(term) and norm(term) in blob:
                score += 2.0
        # Favor evidence with system scope / responsibility / outcome language.
        for signal in ["developed", "led", "implemented", "integrated", "verified", "designed", "delivered", "coordinated", "robust", "reliability", "validation"]:
            if signal in blob:
                score += 0.35
        block_id = ev.get("block_id") or evidence_index.get(evid, {}).get("block_id") or ""
        scored.append((score, evid, {"evidence_id": evid, "text": ev.get("text"), "tags": ev.get("tags", []), "block_id": block_id}))

    scored.sort(key=lambda x: (x[0], x[1]), reverse=True)
    selected = [item for score, _, item in scored if score > 0][:bullet_target]
    # If the score picked too few, fill from original order to give reviewers enough context.
    if len(selected) < bullet_target:
        selected_ids = {s["evidence_id"] for s in selected}
        for block in rg.get("blocks", []):
            for ev in block.get("evidence_items", []):
                if ev["evidence_id"] not in selected_ids:
                    selected.append({"evidence_id": ev["evidence_id"], "text": ev.get("text"), "tags": ev.get("tags", []), "block_id": block.get("block_id")})
                    selected_ids.add(ev["evidence_id"])
                if len(selected) >= bullet_target:
                    break
            if len(selected) >= bullet_target:
                break
    return selected[:bullet_target]


def classify_competence_terms(selected_role_groups: List[str], role_groups: Dict[str, Dict[str, Any]], mandatory_terms: List[str]) -> Dict[str, List[str]]:
    programming: List[str] = []
    knowledge: List[str] = []
    soft: List[str] = []

    for term in mandatory_terms:
        tnorm = norm(term)
        if tnorm in PROGRAMMING_HINTS:
            programming.append(term)
        elif any(h in tnorm for h in SOFT_SKILL_HINTS):
            soft.append(term)
        else:
            knowledge.append(term)

    for rgid in selected_role_groups:
        rg = role_groups[rgid]
        for block in rg.get("blocks", []):
            programming.extend(flatten_strings(block.get("languages", [])))
            programming.extend(flatten_strings(block.get("languages_or_modeling", [])))
            knowledge.extend(flatten_strings(block.get("domains", [])))
            knowledge.extend(flatten_strings(block.get("tools", [])))
            knowledge.extend(flatten_strings(block.get("processes_standards", [])))
            knowledge.extend(flatten_strings(block.get("verification_validation", [])))
            for skill in flatten_strings(block.get("skills", [])):
                if any(h in norm(skill) for h in SOFT_SKILL_HINTS):
                    soft.append(skill)
                else:
                    knowledge.append(skill)
            for ev in block.get("evidence_items", []):
                for tag in ev.get("tags", []) or []:
                    if any(h in norm(tag) for h in SOFT_SKILL_HINTS):
                        soft.append(tag)

    return {
        "Programming": unique_preserve(programming)[:10],
        "Knowledge": unique_preserve(knowledge)[:10],
        "Soft Skills": unique_preserve(soft)[:10],
    }


def infer_deemphasis(job_std: Dict[str, Any]) -> List[str]:
    text = norm(job_std)
    out: List[str] = []
    for trigger, topics in DEEMPHASIS_RULES:
        if trigger in text:
            out.extend(topics)
    if "manager" not in text and "people" not in text:
        out.append("pure people management")
    return unique_preserve(out)


def build_strategy(job_std: Dict[str, Any], match_result: Dict[str, Any], exp: Dict[str, Any], policy: Dict[str, Any]) -> Dict[str, Any]:
    role_groups, blocks, evidence_index = index_experience(exp)
    max_groups = int(get_nested(policy, "cv_generation_policy", "experience", "max_role_groups", default=3) or 3)
    top_bullets = int(get_nested(policy, "cv_generation_policy", "experience", "top_roles_bullets", default=4) or 4)
    additional_bullets = int(get_nested(policy, "cv_generation_policy", "experience", "additional_roles_bullets", default=2) or 2)
    foundational_min = int(get_nested(policy, "cv_generation_policy", "experience", "foundational_role_min_bullets_when_used", default=3) or 3)

    job_id = get_nested(job_std, "job_standardized", "job_id", default=get_nested(match_result, "match_result", "job_id", default="unknown_job"))
    employee_id = get_nested(match_result, "match_result", "employee_id", default="norberto_munoz")
    role_archetype = get_nested(job_std, "job_standardized", "job_analysis", "role_archetype", default="Unclassified role")
    primary_focus = get_nested(job_std, "job_standardized", "job_analysis", "primary_technical_focus", default=[])
    secondary_focus = get_nested(job_std, "job_standardized", "job_analysis", "secondary_technical_focus", default=[])

    mandatory_terms = extract_explicit_terms(job_std, match_result)
    role_group_scores = score_role_groups(match_result, role_groups)
    selected_rgids = select_role_groups(role_group_scores, role_groups, max_groups)
    competence = classify_competence_terms(selected_rgids, role_groups, mandatory_terms)

    selected_role_groups: List[Dict[str, Any]] = []
    experience_plan: List[Dict[str, Any]] = []
    all_selected_evidence: List[str] = []
    for idx, rgid in enumerate(selected_rgids, start=1):
        rg = role_groups[rgid]
        bullet_target = top_bullets if idx <= 2 else additional_bullets
        if rg.get("role_group_type") == "foundational":
            bullet_target = max(bullet_target, foundational_min)
        evidence_items = select_evidence_for_role(
            rgid, role_group_scores, role_groups, evidence_index, mandatory_terms, bullet_target
        )
        all_selected_evidence.extend([e["evidence_id"] for e in evidence_items])
        matched_blocks = role_group_scores.get(rgid, {}).get("matched_blocks", [])
        if not matched_blocks:
            matched_blocks = [b.get("block_id") for b in rg.get("blocks", []) if b.get("block_id")]
        selected_role_groups.append({
            "role_group_id": rgid,
            "priority": idx,
            "role_header": f"{rg.get('display_role_title')}, {rg.get('company')}, {rg.get('time_range')}",
            "role_group_type": rg.get("role_group_type"),
            "recency_rank": rg.get("recency_rank"),
            "selection_score": role_group_scores.get(rgid, {}).get("score", 0),
            "matched_terms": role_group_scores.get(rgid, {}).get("matched_terms", []),
            "emphasis_block_ids": matched_blocks,
            "selection_reason": f"Selected because it supports {', '.join(role_group_scores.get(rgid, {}).get('matched_terms', [])[:8]) or role_archetype}.",
        })
        experience_plan.append({
            "role_group_id": rgid,
            "role_header": f"{rg.get('display_role_title')}, {rg.get('company')}, {rg.get('time_range')}",
            "planned_bullet_count": len(evidence_items),
            "evidence_to_use": evidence_items,
        })

    supported_terms = set()
    for rgid in selected_rgids:
        for term in role_group_scores.get(rgid, {}).get("matched_terms", []):
            supported_terms.add(norm(term))
    missing_mandatory = [term for term in mandatory_terms if norm(term) not in supported_terms]

    strategy = {
        "cv_strategy": {
            "strategy_id": f"strategy_{job_id}",
            "job_id": job_id,
            "employee_id": employee_id,
            "created_at": dt.datetime.now(dt.timezone.utc).isoformat(),
            "status": "draft_for_human_review",
            "input_refs": {
                "job_standardized": f"{job_id}.job_standardized.yaml",
                "match_result": f"{job_id}.match_result.yaml",
                "experience_database": "experience_database.yaml",
                "cv_generation_policy": "cv_generation_policy.yaml",
            },
            "job_positioning": {
                "role_archetype": role_archetype,
                "primary_technical_focus": primary_focus,
                "secondary_technical_focus": secondary_focus,
                "summary_angle": {
                    "generate_dynamically": True,
                    "must_be_grounded_in_selected_evidence": True,
                    "should_emphasize": unique_preserve(flatten_strings([role_archetype, primary_focus, secondary_focus, mandatory_terms[:8]])),
                    "avoid_over_anchoring_to": infer_deemphasis(job_std),
                },
            },
            "selected_role_groups": selected_role_groups,
            "mandatory_cv_terms": mandatory_terms,
            "tech_competence_inclusion": competence,
            "experience_plan": experience_plan,
            "generation_constraints": {
                "max_pages": get_nested(policy, "cv_generation_policy", "max_pages", default=1),
                "max_role_groups": max_groups,
                "do_not_generate_cv_text_yet": True,
                "require_human_approval_before_cv_draft": True,
                "grounding_required": True,
                "forbid_invented_claims": True,
            },
            "validation": {
                "selected_role_group_count": len(selected_rgids),
                "selected_evidence_count": len(unique_preserve(all_selected_evidence)),
                "missing_supported_mandatory_terms_in_selected_roles": missing_mandatory,
                "one_page_strategy_estimate": "pass" if len(selected_rgids) <= max_groups else "fail",
                "review_notes": [
                    "Review selected role groups before generating CV text.",
                    "Check whether mandatory CV terms should appear in summary, tech competence, or bullets.",
                    "Confirm that de-emphasized topics do not dominate the final CV.",
                ],
            },
        }
    }
    return strategy


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a reviewable CV strategy from matcher outputs.")
    parser.add_argument("--job-standardized", required=True, help="Path to *.job_standardized.yaml")
    parser.add_argument("--match-result", required=True, help="Path to *.match_result.yaml")
    parser.add_argument("--data-dir", required=True, help="Directory containing experience_database.yaml and cv_generation_policy.yaml")
    parser.add_argument("--out-dir", required=True, help="Directory where cv_strategy.yaml should be written")
    args = parser.parse_args()

    job_path = Path(args.job_standardized)
    match_path = Path(args.match_result)
    data_dir = resolve_data_dir(args.data_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    job_std = load_yaml(job_path)
    match_result = load_yaml(match_path)
    exp = load_yaml(data_dir / "experience_database.yaml")
    policy = load_yaml(data_dir / "cv_generation_policy.yaml")

    strategy = build_strategy(job_std, match_result, exp, policy)
    job_id = strategy["cv_strategy"]["job_id"]
    out_path = out_dir / f"{job_id}.cv_strategy.yaml"
    write_yaml(out_path, strategy)

    selected = strategy["cv_strategy"]["selected_role_groups"]
    print(f"Wrote {out_path}")
    print("Selected role groups:")
    for rg in selected:
        print(f"  {rg['priority']}. {rg['role_group_id']} - score {rg['selection_score']}")
    missing = strategy["cv_strategy"]["validation"]["missing_supported_mandatory_terms_in_selected_roles"]
    if missing:
        print("Terms not supported by selected role groups:", ", ".join(missing))


if __name__ == "__main__":
    main()
